alias ll="echo ls -halt; ls -halt"
alias gs="git status"
alias gd="git diff"
alias gpush="git push"
alias gpull="git pull"
alias ga="git add"
alias gco="git commit -m"
alias gpm="git pull origin main"
alias gch="git checkout"
alias gph="git push origin head"
alias cl="clear"
alias bb="ssh bb@192.168.0.102"
alias grepy="grep -rni --include='*.py'"
alias grepjs="grep -rni --include='*.js'"
